config/routes.rb
Rails.application.routes.draw do
  resources :offers\
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
    has_one_attached :foto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy ]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:rif, :titolo, :descrizione, :luogo, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/home/_card.html.erb
<div class="card-group">
  <div class="card">
    <img src="https://citynews-trevisotoday.stgy.ovh/~media/square-mid/58534205771612/calling-by-walkie-talkie-2021-08-28-20-05-34-utc-2.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">guidatore scavatore</h5>
      <p class="card-text">autista scavatore con la radio</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="https://kratossafety.com/2567-large_default/sensibilizzazione-ai-lavori-in-altezza.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">muratore</h5>
      <p class="card-text">saper usare la malta</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="https://www.qesco.it/wp-content/uploads/2020/09/qesco-impianti-fotovoltaici-energia-pannelli-solari-solaio-800x800.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">pannelli fotovoltaici</h5>
      <p class="card-text">installatorre pannelli fotovoltaici</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

app/views/home/_carousel.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://keto-mojo.com/wp-content/uploads/2019/12/Mg2.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://www.slowfood.it/slowine/assets/2019/05/UVE-NERE.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://adragna.it/wp-content/uploads/2021/06/agrumi-nel-petfood-2000x800-1.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/index.html.erb
<div class="container">
    <%= render 'carousel'%>
    <%= render 'card'%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <!--<%= image_tag "/img/logo_page.png" %>-->
    <a class="navbar-brand" href="/">FUTURWORK</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/offers">Crea curriculum</a>
        </li>
        
      
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Cerca</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>job</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
 
    <title>FUTURWORK</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :rif, class:'form-label' %>
    <%= form.number_field :rif, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :titolo, class:'form-label' %>
    <%= form.text_field :titolo,  class:'form-control' %>
  </div>

  <div class="mb-3"> 
    <%= form.label :descrizione, class:'form-label' %>
    <%= form.text_area :descrizione,  class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :luogo, class:'form-label' %>
    <%= form.text_field :luogo,  class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :foto, class:'form-label' %>
    <%= form.file_field :foto,  class:'form-control' %>
  </div>
  


  <div class="mb-3">
    <%= form.submit 'Salva', class:'btn btn-primary w-100' %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
  <%if offer.foto.attached? %>
    <%= image_tag url_for(offer.foto), class:'w-100'%>
  <%end%>
  <p>
    <strong>Rif:</strong>
    <%= offer.rif %>
  </p>

  <p>
    <strong>Titolo:</strong>
    <%= offer.titolo %>
  </p>

  <p>
    <strong>Descrizione:</strong>
    <%= offer.descrizione %>
  </p>

  <p>
    <strong>Luogo:</strong>
    <%= offer.luogo %>
  </p>

</div>

app/views/offers/edit.html.erb
<div class="container">
  <h1>Modifica offerta di lavoro</h1>

  <%= render "form", offer: @offer %>

  <br>

  <div>
    <%= link_to "Visualizza offerta", @offer %> |
    <%= link_to "indietro", offers_path %>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Offerte di lavoro</h1>

  <div id="offers" class="row">
    <% @offers.each do |offer| %>
    <div class="col-4">
        <%= render offer %>
        <p>
          <%= link_to "Dettagli", offer,class:'btn btn-primary w-100' %>
        </p>
    </div>
    <% end %>
  </div>

  <%= link_to "nuova offerta", new_offer_path, class:'btn btn-warning w-100'%>
</div>

app/views/offers/new.html.erb
<div class="container">
  <h1>New offer</h1>

  <%= render "form", offer: @offer %>

  <br>

  <div>
    <%= link_to "Torna all'indice", offers_path %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @offer %>

  <div>
    <%= link_to "Modifica", edit_offer_path(@offer),class:'btn btn-warning w-100' %> 
    <div style="padding:20px">

    <%= button_to "Elimina questa offerta", @offer,class:'btn btn-danger w-100', method: :delete %>

    <%= link_to "torna alle offerte", offers_path %>
  </div>
</div>